framework:
    workflows:
        estados_presupuesto:
            type: workflow
            marking_store:
                type: 'method'
                property: 'estado'
            supports:
                - App\Entity\Presupuesto
            initial_marking: pendiente
            places:
                - pendiente
                - aprobado
                - rechazado
            transitions:
                aprobar:
                    from: pendiente
                    to: aprobado
                rechazar:
                    from: pendiente
                    to: rechazado
        estados_proyecto:
            type: workflow
            marking_store:
                type: 'method'
                property: 'estado'
            supports:
                - App\Entity\Proyecto
            initial_marking: aprobado
            places:
                - aprobado
                - enproceso
                - terminado
            transitions:
                iniciar:
                    from: aprobado
                    to: enproceso
                terminar:
                    from: enproceso
                    to: terminado
        estados_tarea:
            type: workflow
            marking_store:
                type: 'method'
                property: 'estado'
            supports:
                - App\Entity\Tarea
            initial_marking: sinasignar
            places:
                - sinasignar
                - asignada
                - terminada
            transitions:
                asignar:
                    from: sinasignar
                    to: asignada
                terminar:
                    from: asignada
                    to: terminada
                reasignar:
                    from: terminada
                    to: asignada