version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/scripts/:/docker-entrypoint-initdb.d/
      - ./docker/mysql/data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
